id: P010504
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016181
  title: ཤར་ཕྱོགས་དུང་རི་དང་དགོན་སྡེ་དུ་མའི་དཀར་ཆག་མཐོང་བ་དོན་ལྡན
  author: ''
  volumes:
    fd376afa24d5433a8ee30466ea6950a5:
      image_group_id: I1PD10388
      title: ''
      volume_number: 1
      total_pages: 183
      base_file: v001.txt
