id: IB78A3697
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:56:24+00:00'
last_modified: '2022-06-08T14:05:07.721059+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016181
  title: ཤར་ཕྱོགས་དུང་རི་དང་དགོན་སྡེ་དུ་མའི་དཀར་ཆག་མཐོང་བ་དོན་ལྡན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D714:
      image_group_id: I1PD10388
      title: ''
      total_pages: 183
      order: 1
      base_file: D714.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
